remote_theme: thelehhman/plainwhite-jekyll
show_excerpts: true

# Seo
title: "César Miquel's blog"
description: "This blog as entries of things I find interesting and might want to revisit later. I also posts some of my experiments in generative art coding and demos."
logo: "/assets/portfolio.png"
author: César Miquel
twitter:
    card: summary
    username: cesarmiquel

plainwhite:
  name: César Miquel
  portfolio_image:  "assets/portfolio.png"
  tagline: |
    Sr. Developer
    @easytechgreen 
  date_format: "%d/%m/%Y"

  social_links:
    twitter: cesarmiquel
    github: cesarmiquel
    instagram: cesarmiquel
    facebook: cesar.miquel.9

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

