remote_theme: riggraz/no-style-please
show_excerpts: true

# Seo
title: "César Miquel's blog"
description: "This blog as entries of things I find interesting and might want to revisit later. I also posts some of my experiments in generative art coding and demos."
logo: "/assets/portfolio.png"
author: César Miquel
twitter:
    card: summary
    username: cesarmiquel

plainwhite:
  name: César Miquel
  portfolio_image:  "assets/portfolio.png"
  dark_mode: true
  tagline: |
    Sr. Developer
    @easytechgreen 
  date_format: "%d/%m/%Y"
  condensed_mobile:
    - home
    - post
    - page


  social_links:
    twitter: cesarmiquel
    github: cesarmiquel
    instagram: cesarmiquel
    facebook: cesar.miquel.9

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

