remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: César Miquel
  show_excerpts: true
  tagline: |
    Sr. Developer
    @easytechgreen 
  date_format: "%d/%m/%Y"

  social_links:
    twitter: cesarmiquel
    github: cesarmiquel
