remote_theme: thelehhman/plainwhite-jekyll
show_excerpts: true

plainwhite:
  name: César Miquel
  tagline: |
    Sr. Developer
    @easytechgreen 
  date_format: "%d/%m/%Y"

  social_links:
    twitter: cesarmiquel
    github: cesarmiquel
    instagram: cesarmiquel
    facebook: cesar.miquel.9

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

